package edu.westga.cs3212.meal_planning.view;

import java.io.IOException;


import javafx.fxml.FXML;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;

/** Codebehind for the CategorySelectScreen.
 * 
 * @author jcorley
 */
public class CategorySelectScreen {

    @FXML private ListView<String> categories;

	/** Opens the Recipe Select Screen if a valid (not null) category has been selected.
	 * 
	 * @param event event generated by the associated javafx control
	 * 
	 * @throws IOException thrown if the fxml for the RecipeSelectScreen is not available or improperly formatted.
	 */
    @FXML
    void selectCategory(MouseEvent event) throws IOException {
    	String category = this.categories.getSelectionModel().getSelectedItem();
    	if (category != null) {
	    	ScreenUtilities.openRecipeSelectScreen(event, category);
    	}
    }

    /**Automated setup run when JavaFX engine generates this controller. 
     * Verifies all javafx controls are initialized, and adds the list of categories to the view.
     */
    @FXML
    void initialize() {
        assert this.categories != null : "fx:id=\"categoryList\" was not injected: check your FXML file 'CategorySelectScreen.fxml'.";

        this.categories.getItems().addAll(RecipeStore.getRecipeManager().getCategories());
    }

}
