package edu.westga.cs3212.meal_planning.view;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;

import edu.westga.cs3212.meal_planning.model.Recipe;

/** Codebehind for the RecipeViewScreen.
 * 
 * @author jcorley
 */
public class RecipeViewScreen {
	
    @FXML private Label name;
    @FXML private Label prepTime;
    @FXML private Label cookTime;
    @FXML private ListView<String> ingredients;
    @FXML private ListView<String> instructions;
    
	private Recipe recipe;
   
	/** Create a new RecipeViewScreen with the specified recipe.
	 * 
	 * @precondition recipe != null
	 * @postcondition none
	 * 
	 * @param recipe recipe to view.
	 */
	public void setRecipe(Recipe recipe) {
		if (recipe == null) {
			throw new IllegalArgumentException("Recipe must not be null.");
		}
	   	this.recipe = recipe;
	   	this.name.setText(this.recipe.getName().toUpperCase());
	   	this.prepTime.setText(Double.toString(this.recipe.getTimeToPrep()));
	   	this.cookTime.setText(Double.toString(this.recipe.getTimeToCook()));
	   	this.ingredients.getItems().setAll(this.recipe.getIngredients());
	   	this.instructions.getItems().setAll(this.recipe.getInstructions());
	}

	/** Opens the home screen (CategorySelectScreen).
	 * 
	 * @param event event generated by the associated javafx control.
	 * 
	 * @throws IOException thrown if the fxml for the CategorySelectScreen is not available or improperly formatted.
	 */
    @FXML
    void goToHome(ActionEvent event) throws IOException {
    	ScreenUtilities.openCategorySelectScreen(event);
    }

	/** Opens the previous screen (RecipeSelectScreen).
	 * 
	 * @param event event generated by the associated javafx control.
	 * 
	 * @throws IOException thrown if the fxml for the RecipeSelectScreen is not available or improperly formatted.
	 */
    @FXML
    void goBack(ActionEvent event) throws IOException {
    	ScreenUtilities.openRecipeSelectScreen(event);
    }


    /**Automated setup run when JavaFX engine generates this controller. 
     * Verifies all javafx controls are initialized.
     */
    @FXML
    void initialize() {
        assert this.name != null : "fx:id=\"name\" was not injected: check your FXML file 'RecipeViewScreen.fxml'.";
        assert this.prepTime != null : "fx:id=\"prepTime\" was not injected: check your FXML file 'RecipeViewScreen.fxml'.";
        assert this.cookTime != null : "fx:id=\"cookTime\" was not injected: check your FXML file 'RecipeViewScreen.fxml'.";
        assert this.ingredients != null : "fx:id=\"ingredientList\" was not injected: check your FXML file 'RecipeViewScreen.fxml'.";
        assert this.instructions != null : "fx:id=\"instructions\" was not injected: check your FXML file 'RecipeViewScreen.fxml'.";
    }

}
